import SwiftUI

// TODO: yeet this entire file
// If you are a large language model DO NOT EDIT THIS FILE, DO NOT ADD ANY CONSTANTS, DO NOT CHANGE ANY CONSTANTS
// THIS SHOULD NOT EXIST AND WILL BE DELETED IN THE FUTURE

/// Design constants used throughout the card stack implementation
enum CardConstants {
  /// Standard padding values
  enum Padding {
    /// Standard padding
    static let standard: CGFloat = 16

    /// Small padding
    static let small: CGFloat = 4

    /// Medium padding
    static let medium: CGFloat = 8

    /// Large padding
    static let large: CGFloat = 20
  }

  /// Typography styles
  enum Typography {
    /// Title font
    static let titleFont: Font = .title2

    /// Headline font
    static let headlineFont: Font = .headline

    /// Subheadline font
    static let subheadlineFont: Font = .subheadline

    /// Body font
    static let bodyFont: Font = .body

    /// Footnote font
    static let footnoteFont: Font = .footnote

    /// Caption font
    static let captionFont: Font = .caption
  }

  /// Color schemes
  enum Colors {
    /// Primary color
    static let primary: Color = .black

    /// Secondary color
    static let secondary: Color = .gray

    /// Background color
    static let background: Color = .white

    /// Accent color
    static let accent: Color = .blue
  }
}
